# Le poids du parc social dans l'ensemble du parc {#poidsduparc}

```{r map_poids,fig.width=12,fig.height=7}
composeur_carte(
  .data = indicateurs_rpls,
  indicateur = "Nombre de logements sociaux",
  titre = "Part des logements hlm dans les résidences principales au 1er janvier 2018",
  soustitre = "En %",
  parc_recent = F,
  basdepage = NULL,
  filtre_zero = F,
  na_recode = "Aucun logement\nsocial"
)
```

```{r poids_du_parc, fig.align="right",fig.width=12,fig.height=6}
df %>%
  filter(
    SousEnsemble %in% c("Ensemble du parc"),
    Indicateur == "Nombre de logements sociaux",
    (TypeZone %in% c("Départements", "Régions", "France") | (TypeZone == "Epci" & CodeZone %in% epci_ref$EPCI))
  ) %>%
  ggplot() +
  geom_segment(aes(x = Zone, xend = Zone, y = 0, yend = Pourcent, color = TypeZone)) +
  geom_point(aes(x = Zone, y = Pourcent, fill = TypeZone), color = "white", pch = 21) +
  theme_graph() +
  coord_flip() +
  scale_color_dreal_d() +
  scale_fill_dreal_d() +
  theme(legend.position = "none") +
  labs(x = "", y = "", title = str_wrap("Poids du parc social dans l'ensemble du parc", 30), caption = caption_poids)
```
