# Taux de mobilité dans le parc {#mobilite}

```{r map_mobilite,fig.width=14,fig.height=9}
composeur_carte(
  .data = indicateurs_rpls,
  indicateur = "Taux de mobilité",
  titre = "Taux de mobilité dans le parc social",
  soustitre = "En %",
  parc_recent = F,
  basdepage = NULL,
  variable = Valeur,
  filtre_zero = T,
  na_recode = "Pas de logements"
)
```

```{r graph_mobilite, fig.align="right",fig.width=12,fig.height=6}
df %>%
  filter(
    SousEnsemble %in% c("Ensemble du parc"),
    Indicateur == "Taux de mobilité",
    (TypeZone %in% c("Départements", "Régions", "France") | (TypeZone == "Epci" & CodeZone %in% epci_ref$EPCI))
  ) %>%
  ggplot() +
  geom_segment(aes(x = Zone, xend = Zone, y = 0, yend = Valeur, color = TypeZone),size=1.5) +
  geom_point(aes(x = Zone, y = Valeur, fill = TypeZone), color = "white", pch = 21,size=4) +
  theme_graph() +
  coord_flip() +
  scale_color_dreal_d() +
  scale_fill_dreal_d() +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 2)) +
  labs(x = "", y = "", title = str_wrap("Taux de mobilité dans l'ensemble du parc", 60), caption = caption)

```



