#' Importer une ficher rpls 2017 geolocalisé csv en Rdata
#'
#' @param file le fichier csv
#' @param as_sf booléen TRUE si on souhaite convertir le dataframe en spatial dataframe (pour les données géolocalisées)
#'
#' @return la fonction renvoie un dataframe ou un spatial dataframe
#'
#' @importFrom readr read_delim
#' @importFrom readr locale
#' @importFrom readr col_character
#' @importFrom readr col_factor
#' @importFrom readr col_date
#' @importFrom readr col_integer
#' @importFrom readr col_number
#' @importFrom readr locale
#' @importFrom dplyr funs
#' @importFrom dplyr mutate_at
#' @importFrom dplyr filter
#' @importFrom sf st_as_sf
#' @import magrittr

lire_rpls_2017_geoloc<-function(file,as_sf=F){
  facteurs<-c("CONV_red",
              "DEP",
              "DEPCOM_red",
              "DPEENERGIE_red",
              "DPESERRE_red",
              "DROIT_red",
              "EPCI16",
              "IDENTGES_red",
              "IDENT_INT",
              "IDENT_ORG",
              "IDENT_REP",
              "INDREP_red",
              "LIB_EPCI16",
              "MISCOMMERCIAL_red",
              "MODE_red",
              "NEWLOGT_red",
              "OLDLOGT_red",
              "PLG_CODE_COMMUNE",
              "QPV_red",
              "QUALACQ_red",
              "QUALITE_IRIS",
              "QUALITE_NUMERO",
              "QUALITE_QP",
              "QUALITE_QVA",
              "QUALITE_VOIE",
              "QUALITE_ZFU",
              "QUALITE_ZUS",
              "REG",
              "ROL",
              "raison_sociale",
              "RSEXPRO_red",
              "SIRETEXPRO_red",
              "SORTIEPATRIM_red",
              "SRU_ALINEA_red",
              "TYPECONST_red",
              "TYPVOIE_red",
              "dep_commune",
              "dep_epci",
              "depcom_red16",
              "depcom_red17",
              "epci17",
              "finan_red",
              "iris",
              "lib_com16",
              "lib_com17",
              "lib_dep",
              "lib_epci17",
              "lib_reg",
              "lib_reg16",
              "lib_reg2016",
              "libepci17",
              "modesurf_red",
              "nbpiece_red",
              "origine_red",
              "patrimoine_red",
              "qp",
              "qva",
              "reg16",
              "reg2016",
              "siret",
              "zfu",
              "zus")

  rpls<-read_delim(file, delim=";",
                   locale=locale(date_names = "fr", date_format = "%d/%m/%Y",
                                 time_format = "%AT",decimal_mark = ".",
                                 grouping_mark = " ", tz = "UTC",encoding = "latin1", asciify = FALSE),
                   col_types = list(
                     BAT_red=col_character(),
                     CAT_ORG=col_character(),
                     CODEPOSTAL_red=col_character(),
                     CODSEGPATRIM_red=col_character(),
                     COMAQP=col_character(),
                     COMPLGEO_red=col_character(),
                     COMPLIDENT_red=col_character(),
                     COMRIL=col_character(),
                     CONTRESLOG_red=col_character(),
                     CONTRIB_red=col_character(),
                     CONV_red=col_character(),
                     COULOIR_red=col_character(),
                     CUS_SIGNEE=col_character(),
                     CUS_red=col_character(),
                     DATCONV_red=col_date(),
                     DEP=col_character(),
                     DEPCOM_red=col_character(),
                     DISTANCE_PRECISION=col_number(),
                     DPEDATE_red=col_date(format="%m/%Y"),
                     DPEENERGIE_red=col_character(),
                     DPESERRE_red=col_character(),
                     DROIT_red=col_character(),
                     ENTREE_red=col_character(),
                     EPCI16=col_character(),
                     ESC_red=col_character(),
                     ETAGE_red=col_character(),
                     FINANAUTRE_red=col_character(),
                     IDENTGES_red=col_character(),
                     IDENT_INT=col_character(),
                     IDENT_ORG=col_character(),
                     IDENT_REP=col_character(),
                     IMMEU_red=col_character(),
                     INDREP_red=col_character(),
                     LIBSEGPATRIM_red=col_character(),
                     LIB_EPCI16=col_character(),
                     LIEUDIT_red=col_character(),
                     LOYERMAXCUS_red=col_number(),
                     MISCOMMERCIAL_red=col_character(),
                     MODE_red=col_character(),
                     NEWLOGT_red=col_character(),
                     NOMVOIE_red=col_character(),
                     NUMAPPT_red=col_character(),
                     NUMBOITE_red=col_character(),
                     NUMCONV_red=col_character(),
                     NUMVOIE_red=col_character(),
                     OLDLOGT_red=col_character(),
                     PLG_CODE_COMMUNE=col_character(),
                     PLG_VOIE=col_character(),
                     PRIXVENTE_red=col_number(),
                     PRODFIN_red=col_number(),
                     QPV_red=col_character(),
                     QUALACQ_red=col_character(),
                     QUALITE_IRIS=col_character(),
                     QUALITE_NUMERO=col_character(),
                     QUALITE_QP=col_character(),
                     QUALITE_QVA=col_character(),
                     QUALITE_VOIE=col_character(),
                     QUALITE_ZFU=col_character(),
                     QUALITE_ZUS=col_character(),
                     REG=col_character(),
                     ROL=col_character(),
                     raison_sociale=col_character(),
                     RSEXPRO_red=col_character(),
                     SIRETEXPRO_red=col_character(),
                     SORTIEPATRIM_red=col_character(),
                     SRU_ALINEA_red=col_character(),
                     SRU_EXPIR_red=col_integer(),
                     TYPECONST_red=col_character(),
                     TYPVOIE_red=col_character(),
                     age=col_integer(),
                     bail_red=col_date(format="%m/%Y"),
                     cnt_rep=col_character(),
                     construct_red=col_integer(),
                     dep_commune=col_character(),
                     dep_epci=col_character(),
                     depcom_red16=col_character(),
                     depcom_red17=col_character(),
                     duree_vacance=col_integer(),
                     epci17=col_character(),
                     epsg=col_integer(),
                     finan_red=col_character(),
                     iris=col_character(),
                     lib_com16=col_character(),
                     lib_com17=col_character(),
                     lib_dep=col_character(),
                     lib_epci17=col_character(),
                     lib_reg=col_character(),
                     lib_reg16=col_character(),
                     lib_reg2016=col_character(),
                     libepci17=col_character(),
                     locat_red=col_integer(),
                     loyeracc_red=col_number(),
                     loyermaxapl_red=col_number(),
                     loyerprinc_red=col_number(),
                     loymoy=col_number(),
                     mes_sanscumul=col_character(),
                     mes_sanscumul_prec=col_character(),
                     modesurf_red=col_character(),
                     nbpiece_red=col_character(),
                     origine_red=col_character(),
                     patrimoine_red=col_character(),
                     qp=col_character(),
                     qva=col_character(),
                     reg16=col_character(),
                     reg2016=col_character(),
                     remlocdate_red=col_date(format="%m/%Y"),
                     siret=col_character(),
                     surfhab_red=col_number(),
                     surfmode_red=col_number(),
                     x=col_number(),
                     y=col_number(),
                     zfu=col_character(),
                     zus=col_character())
  ) %>%
    mutate_at(facteurs,funs(as.factor)) %>%
    filter(!is.na(x)&!is.na(y))

  if (as_sf==T) {
    rpls<-st_as_sf(rpls,coords=c("x","y"),crs=2154)
    return(rpls)
  }
  else {
    return(rpls)
  }
}


